;; Auto-generated by spel codegen

(require '[com.blockether.spel.assertions :as assert])
(require '[com.blockether.spel.core :as core])
(require '[com.blockether.spel.locator :as locator])
(require '[com.blockether.spel.page :as page])
(import '[com.microsoft.playwright Page])
(import '[com.microsoft.playwright.options AriaRole])

(core/with-playwright [pw]
  (core/with-browser [browser (core/launch-chromium pw {:headless false})]
    (core/with-context [ctx (core/new-context browser)]
      (core/with-page [pg (core/new-page-from-context ctx)]
      ;; New page: pg
      (page/navigate pg "https://github.com/")
      (assert/is-visible (assert/assert-that (page/get-by-role pg AriaRole/NAVIGATION {:name "Platform"})))
      (locator/click (page/get-by-role pg AriaRole/LINK {:name "Sign in"}))
      (assert/is-visible (assert/assert-that (page/get-by-role pg AriaRole/BUTTON {:name "Continue with Google"})))
      (locator/click (page/get-by-role pg AriaRole/TEXTBOX {:name "Username or email address"}))
      (locator/fill (page/get-by-role pg AriaRole/TEXTBOX {:name "Username or email address"}) "karol.wojcik@tuta.io")
      (locator/press (page/get-by-role pg AriaRole/TEXTBOX {:name "Username or email address"}) "Tab")
      (locator/fill (page/get-by-role pg AriaRole/TEXTBOX {:name "Password"}) "dadad")
      (locator/press (page/get-by-role pg AriaRole/TEXTBOX {:name "Password"}) "Enter")
      (locator/click (page/get-by-role pg AriaRole/BUTTON {:name "Sign in", :exact true}))
      (assert/is-visible (assert/assert-that (page/get-by-role pg AriaRole/BUTTON {:name "Continue with Google"})))
      (locator/click (page/get-by-text pg "Incorrect username or"))
      (assert/contains-text (assert/assert-that (page/get-by-role pg AriaRole/ALERT)) "Incorrect username or password.")))))
