Args = --features=clj_easy.graal_build_time.InitClojureClasses \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=com.microsoft.playwright.options \
       --initialize-at-build-time=org.eclipse.aether.util.version.GenericVersionScheme
