(ns com.blockether.spel.markdownify
  "Convert HTML documents into readable Markdown using the browser runtime."
  (:require
   [clojure.string :as str]
   [com.blockether.spel.page :as page]))

(def ^:private html->markdown-js
  (str/join
    "\n"
    ["(arg) => {"
     "  const html = arg && arg[0] != null ? String(arg[0]) : '';"
     "  const includeTitle = !!(arg && arg[1]);"
     "  const readableOnly = !!(arg && arg[2]);"
     "  const parser = new DOMParser();"
     "  const doc = parser.parseFromString(html, 'text/html');"
     "  const blocks = new Set(['article','aside','blockquote','body','div','dl','dt','dd','fieldset','figcaption','figure','footer','form','header','main','nav','ol','p','pre','section','table','tbody','td','tfoot','th','thead','tr','ul']);"
     "  const skip = new Set(['script','style','noscript','iframe','svg','canvas']);"
     "  function collapse(text) { return String(text || '').replace(/\\s+/g, ' ').trim(); }"
     "  function scoreNode(el) {"
     "    if (!el || !el.textContent) return 0;"
     "    const text = collapse(el.textContent);"
     "    if (!text) return 0;"
     "    const links = el.querySelectorAll ? el.querySelectorAll('a').length : 0;"
     "    const densityPenalty = Math.min(links * 10, 300);"
     "    return text.length - densityPenalty;"
     "  }"
     "  function pickRoot(document) {"
     "    if (!readableOnly) return document.body || document.documentElement;"
     "    const candidates = Array.from(document.querySelectorAll('article,main,[role=\"main\"],.article,.post,.content,.main,.main-content'));"
     "    let best = null;"
     "    let bestScore = 0;"
     "    candidates.forEach((el) => {"
     "      const s = scoreNode(el);"
     "      if (s > bestScore) { best = el; bestScore = s; }"
     "    });"
     "    if (best && bestScore > 200) return best;"
     "    return document.body || document.documentElement;"
     "  }"
     "  function pruneNoise(root) {"
     "    if (!readableOnly || !root || !root.querySelectorAll) return;"
     "    const noise = root.querySelectorAll('nav,aside,footer,[aria-hidden=\"true\"],.advertisement,.ads,.cookie,.cookie-banner');"
     "    noise.forEach((el) => el.remove());"
     "  }"
     "  function inline(node) {"
     "    if (!node) return '';"
     "    if (node.nodeType === Node.TEXT_NODE) return collapse(node.textContent);"
     "    if (node.nodeType !== Node.ELEMENT_NODE) return '';"
     "    const tag = node.tagName.toLowerCase();"
     "    if (skip.has(tag)) return '';"
     "    if (tag === 'br') return '\\n';"
     "    if (tag === 'code' && node.parentElement && node.parentElement.tagName.toLowerCase() !== 'pre') return '`' + collapse(node.textContent) + '`';"
     "    if (tag === 'a') {"
     "      const text = collapse(Array.from(node.childNodes).map(inline).join(' ')) || node.getAttribute('href') || '';"
     "      const href = node.getAttribute('href') || '';"
     "      return '[' + text + '](' + href + ')';"
     "    }"
     "    if (tag === 'img') return '![' + (node.getAttribute('alt') || '') + '](' + (node.getAttribute('src') || '') + ')';"
     "    const content = collapse(Array.from(node.childNodes).map(inline).join(' '));"
     "    if (tag === 'strong' || tag === 'b') return content ? '**' + content + '**' : '';"
     "    if (tag === 'em' || tag === 'i') return content ? '*' + content + '*' : '';"
     "    return content;"
     "  }"
     "  function render(node, depth) {"
     "    depth = depth || 0;"
     "    if (!node) return '';"
     "    if (node.nodeType === Node.TEXT_NODE) return collapse(node.textContent);"
     "    if (node.nodeType !== Node.ELEMENT_NODE) return '';"
     "    const tag = node.tagName.toLowerCase();"
     "    if (skip.has(tag)) return '';"
     "    if (/^h[1-6]$/.test(tag)) {"
     "      const level = Number(tag[1]);"
     "      const text = collapse(node.textContent);"
     "      return text ? '#'.repeat(level) + ' ' + text + '\\n\\n' : '';"
     "    }"
     "    if (tag === 'p') {"
     "      const text = collapse(Array.from(node.childNodes).map(inline).join(' '));"
     "      return text ? text + '\\n\\n' : '';"
     "    }"
     "    if (tag === 'blockquote') {"
     "      const text = collapse(Array.from(node.childNodes).map(inline).join(' '));"
     "      return text ? '> ' + text + '\\n\\n' : '';"
     "    }"
     "    if (tag === 'pre') {"
     "      const text = node.textContent || '';"
     "      return text ? '```\\n' + text.replace(/^\\n+|\\n+$/g, '') + '\\n```\\n\\n' : '';"
     "    }"
     "    if (tag === 'hr') return '---\\n\\n';"
     "    if (tag === 'ul' || tag === 'ol') {"
     "      const ordered = tag === 'ol';"
     "      const items = Array.from(node.children).filter((el) => el.tagName && el.tagName.toLowerCase() === 'li');"
     "      return items.map((li, idx) => {"
     "        const prefix = '  '.repeat(depth) + (ordered ? (idx + 1) + '. ' : '- ');"
     "        const text = collapse(Array.from(li.childNodes).map((child) => child.nodeType === Node.ELEMENT_NODE && ['ul','ol'].includes(child.tagName.toLowerCase()) ? '' : inline(child)).join(' '));"
     "        const nested = Array.from(li.children).filter((el) => ['ul','ol'].includes(el.tagName.toLowerCase())).map((el) => render(el, depth + 1)).join('');"
     "        return prefix + text + '\\n' + nested;"
     "      }).join('') + '\\n';"
     "    }"
     "    if (tag === 'table') {"
     "      const rows = Array.from(node.querySelectorAll('tr')).map((tr) => Array.from(tr.querySelectorAll('th,td')).map((td) => collapse(td.textContent))).filter((row) => row.length);"
     "      if (!rows.length) return '';"
     "      const header = rows[0];"
     "      const body = rows.slice(1);"
     "      const out = [];"
     "      out.push('| ' + header.join(' | ') + ' |');"
     "      out.push('| ' + header.map(() => '---').join(' | ') + ' |');"
     "      body.forEach((row) => out.push('| ' + row.join(' | ') + ' |'));"
     "      return out.join('\\n') + '\\n\\n';"
     "    }"
     "    const children = Array.from(node.childNodes).map((child) => blocks.has(tag) ? render(child, depth) : inline(child)).join(blocks.has(tag) ? '' : ' ');"
     "    return children;"
     "  }"
     "  const parts = [];"
     "  const title = collapse(doc.title || '');"
     "  if (includeTitle && title) parts.push('# ' + title);"
     "  const root = pickRoot(doc);"
     "  pruneNoise(root);"
     "  Array.from(root ? root.childNodes : []).forEach((node) => {"
     "    const rendered = render(node, 0).trim();"
     "    if (rendered) parts.push(rendered);"
     "  });"
     "  const out = parts.join('\\n\\n').replace(/\\n{3,}/g, '\\n\\n').trim();"
     "  return out ? out + '\\n' : '';"
     "}"]))

(defn html->markdown
  "Converts an HTML string into Markdown using an existing Playwright page.

   Options:
   - :title? include document title as a top-level heading (default true)
   - :readable? prefer main content over full page chrome (default true)"
  ([pg html] (html->markdown pg html {}))
  ([pg html {:keys [title? readable?] :or {title? true readable? true}}]
   (page/evaluate pg html->markdown-js [html title? readable?])))
