(ns com.blockether.spel.roles
  "Clojure vars wrapping Playwright's AriaRole enum values.

   Eliminates the need for `(:import [com.microsoft.playwright.options AriaRole])`.

   Usage:
     (require '[com.blockether.spel.roles :as role])
     (page/get-by-role pg role/button)
     (page/get-by-role pg role/heading {:name \"Title\"})"
  (:refer-clojure :exclude [list time])
  (:import
   [com.microsoft.playwright.options AriaRole]))

(def alert            AriaRole/ALERT)
(def alertdialog      AriaRole/ALERTDIALOG)
(def application      AriaRole/APPLICATION)
(def article          AriaRole/ARTICLE)
(def banner           AriaRole/BANNER)
(def blockquote       AriaRole/BLOCKQUOTE)
(def button           AriaRole/BUTTON)
(def caption          AriaRole/CAPTION)
(def cell             AriaRole/CELL)
(def checkbox         AriaRole/CHECKBOX)
(def code             AriaRole/CODE)
(def columnheader     AriaRole/COLUMNHEADER)
(def combobox         AriaRole/COMBOBOX)
(def complementary    AriaRole/COMPLEMENTARY)
(def contentinfo      AriaRole/CONTENTINFO)
(def definition       AriaRole/DEFINITION)
(def deletion         AriaRole/DELETION)
(def dialog           AriaRole/DIALOG)
(def directory        AriaRole/DIRECTORY)
(def document         AriaRole/DOCUMENT)
(def emphasis         AriaRole/EMPHASIS)
(def feed             AriaRole/FEED)
(def figure           AriaRole/FIGURE)
(def form             AriaRole/FORM)
(def generic          AriaRole/GENERIC)
(def grid             AriaRole/GRID)
(def gridcell         AriaRole/GRIDCELL)
(def group            AriaRole/GROUP)
(def heading          AriaRole/HEADING)
(def img              AriaRole/IMG)
(def insertion        AriaRole/INSERTION)
(def link             AriaRole/LINK)
(def list             AriaRole/LIST)
(def listbox          AriaRole/LISTBOX)
(def listitem         AriaRole/LISTITEM)
(def log              AriaRole/LOG)
(def main             AriaRole/MAIN)
(def marquee          AriaRole/MARQUEE)
(def math             AriaRole/MATH)
(def meter            AriaRole/METER)
(def menu             AriaRole/MENU)
(def menubar          AriaRole/MENUBAR)
(def menuitem         AriaRole/MENUITEM)
(def menuitemcheckbox AriaRole/MENUITEMCHECKBOX)
(def menuitemradio    AriaRole/MENUITEMRADIO)
(def navigation       AriaRole/NAVIGATION)
(def none             AriaRole/NONE)
(def note             AriaRole/NOTE)
(def option           AriaRole/OPTION)
(def paragraph        AriaRole/PARAGRAPH)
(def presentation     AriaRole/PRESENTATION)
(def progressbar      AriaRole/PROGRESSBAR)
(def radio            AriaRole/RADIO)
(def radiogroup       AriaRole/RADIOGROUP)
(def region           AriaRole/REGION)
(def row              AriaRole/ROW)
(def rowgroup         AriaRole/ROWGROUP)
(def rowheader        AriaRole/ROWHEADER)
(def scrollbar        AriaRole/SCROLLBAR)
(def search           AriaRole/SEARCH)
(def searchbox        AriaRole/SEARCHBOX)
(def separator        AriaRole/SEPARATOR)
(def slider           AriaRole/SLIDER)
(def spinbutton       AriaRole/SPINBUTTON)
(def status           AriaRole/STATUS)
(def strong           AriaRole/STRONG)
(def subscript        AriaRole/SUBSCRIPT)
(def superscript      AriaRole/SUPERSCRIPT)
(def switch           AriaRole/SWITCH)
(def tab              AriaRole/TAB)
(def table            AriaRole/TABLE)
(def tablist          AriaRole/TABLIST)
(def tabpanel         AriaRole/TABPANEL)
(def term             AriaRole/TERM)
(def textbox          AriaRole/TEXTBOX)
(def time             AriaRole/TIME)
(def timer            AriaRole/TIMER)
(def toolbar          AriaRole/TOOLBAR)
(def tooltip          AriaRole/TOOLTIP)
(def tree             AriaRole/TREE)
(def treegrid         AriaRole/TREEGRID)
(def treeitem         AriaRole/TREEITEM)
